spring.application.name=Ressource Relationnelles
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration de Hibernate/JPA
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Mode développement par défaut
dev.mode=false
dev.mode.default-user-id=3

# Logging
logging.level.root=INFO
logging.level.cesi.RessourceRelationnelles=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=DEBUG

# Configuration des profiles
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
